theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
cursorline = true
scrolloff = 10
clipboard-provider= "pasteboard"
bufferline = "always"
preview-completion-insert = false
auto-info = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
q = ":quit!"
y = ":clipboard-yank"
p = ":clipboard-paste-after"
" "." " = "file_picker_in_current_directory"
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.insert]
j.k = "normal_mode"
k.j = "normal_mode"

[keys.select]
y = ":clipboard-yank"
p = ":clipboard-paste-after"


