theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
cursorline = true
scrolloff = 10
# clipboard-provider= "pasteboard"
bufferline = "always"
preview-completion-insert = true
auto-info = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
color-modes = true
# end-of-line-diagnostics = "hint"
# soft-wrap = { enable = true }

[editor.lsp]
# display-inlay-hints = true
enable = true
snippets = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
q = ":quit!"
y = ":clipboard-yank"
p = ":clipboard-paste-before"
" "." " = "file_picker_in_current_directory"
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
" ".l.g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
A-j = "extend_line_down"
A-k = "extend_line_up"
A-a = "expand_selection"
A-d = "jump_backward"
A-f = "jump_forward"
C-j = "@12zj"
C-k = "@12zk"

[keys.insert]
j.k = "normal_mode"
k.j = "normal_mode"

[keys.select]
y = ":clipboard-yank"
p = ":clipboard-paste-before"

