# ======================================
# 🐍 Python: Ruff + Pyright
# ======================================

[language-server.ruff]
command = "ruff"
args = ["server"]
config = { settings = { organizeImports = true, fixAll = true} }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]


# [[language]]
# name = "python"
# language-servers = ["pyright", "ruff"]
# formatter = { command = "ruff", args = ["format", "-"] }
# auto-format = true
# auto-pairs = { '(' = ')', '{' = '}', '[' = ']', '"' = '"', "'" = "'" }
# text-width = 88
# rulers = [88]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "sh", args = ["-c", "ruff check --fix --stdin-filename placeholder.py - | ruff format -"] }
auto-format = true
auto-pairs = { '(' = ')', '{' = '}', '[' = ']', '"' = '"', "'" = "'" }
text-width = 88
rulers = [88]

# ======================================
# 📝 Markdown
# ======================================

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]


# ======================================
# ⚙️ TOML (Taplo)
# ======================================

[language-server.taplo]
# Workaround for nonfunctional behavior outside git directories
# See: https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437
config = {}

[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
