# ======================================
# 🐍 Python: Ruff + Pyright
# ======================================

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

# ======================================
# 📝 Markdown
# ======================================

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]


# ======================================
# ⚙️ TOML (Taplo)
# ======================================

[language-server.taplo]
# Workaround for nonfunctional behavior outside git directories
# See: https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437
config = {}

[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
