#!/bin/bash

layout_uv() {
    if [[ ! -f uv.lock ]]; then
        log_error 'No uv.lock found. Generate one first.'
        exit 2
    fi

    export VIRTUAL_ENV="$PWD/.venv"
    VIRTUAL_ENV_PROMPT=$(basename "$PWD")
    export VIRTUAL_ENV_PROMPT
    PATH_add "$VIRTUAL_ENV/bin"
}

source_env "$HOME"/.env
